# Generated by Django 4.0.8 on 2023-07-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_managers'),
        ('course', '0006_courseoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='accounts.student'),
        ),
    ]
