# Generated by Django 4.0.8 on 2023-07-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
