# Generated by Django 4.2.5 on 2023-10-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_remove_course_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadvideo",
            name="duration",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
