# Generated by Django 4.2.5 on 2023-10-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_remove_uploadvideo_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadvideo",
            name="duration",
            field=models.DurationField(null=True),
        ),
    ]
