# Generated by Django 4.2.5 on 2023-10-21 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_newsandevents_id_alter_semester_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Landing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_Color", models.TextField(blank=True, max_length=500, null=True)),
                ("Hero_Title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Hero_Content",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "Supporter_Logo",
                    models.FileField(
                        upload_to="LandingPage/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["svg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "Course_Top_Card",
                    models.FileField(
                        upload_to="LandingPage/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["svg", "png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                (
                    "why_choose_Us",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "why_choose_us_img",
                    models.FileField(
                        upload_to="LandingPage/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["svg", "png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
